title: Senza cattedra
tagline: Percorsi per una scuola possibile
remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

