title: Senza cattedra
header:
  overlay_image: /assets/img/header.jpg
  caption: "La scuola possibile"

remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

