title: Senza cattedra
header:
  overlay_image: /assets/img/header.jpg
  caption: "Un altro modo di fare scuola"
  overlay_filter: 0.3


remote_theme: "jeffreytse/jekyll-theme-yat@v1.10.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

